#!/bin/bash
# Script to extract and format Pokémon data using jq, awk, sed

jq -r '
  .name, .types[0].type.name, .weight, .height
' data.json | awk '
NR==1 { name=$0 }
NR==2 { type=$0 }
NR==3 { weight_kg = int($0 / 10) }
NR==4 { height_m = $0 / 10 }
END {
  printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", name, type, weight_kg, height_m
}
' | sed -E 's/^(.)/\U\1/; s/ of type (.)/ of type \U\1/'
