#!/bin/bash
# Script to extract and print formatted Pokémon data using jq, awk, sed with required variable names

read name type weight height < <(
  jq -r '.name, .types[0].type.name, .weight, .height' data.json
)

# Use required variable names
formatted_weight=$(( weight / 10 ))
formatted_height=$(awk "BEGIN { printf \"%.1f\", $height / 10 }")

# Capitalize name and type using sed
name=$(echo "$name" | sed -E 's/^(.)/\U\1/')
type=$(echo "$type" | sed -E 's/^(.)/\U\1/')

# Final output using required variable names
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
