#!/bin/bash
# Extract and print human-readable Pokémon data from data.json

jq -r '
  .name as $name |
  .height as $height |
  .weight as $weight |
  .types[0].type.name as $type |
  [$name, $type, ($weight / 10), ($height / 10)] |
  @tsv
' data.json | awk -F '\t' '
{
  name = toupper(substr($1,1,1)) tolower(substr($1,2))
  type = toupper(substr($2,1,1)) tolower(substr($2,2))
  weight = int($3)
  height = $4
  printf "%s is of type %s, weighs %dkg, and is %.1fm tall.\n", name, type, weight, height
}'
